image:
  widths: [600, 900, 1300]
  # shortcode_widths: [600, 900, 1300]
  # render_hook_widths: [600, 900, 1300]
  densities: [1, 2]
  formats: [original, webp]
  class: img-fluid
  figure_class: figure
  figcaption_class: figure-caption
  figure_image_class: "figure-img img-fluid"
  figure_title_class: 4
  render_hook_wrapper_class: img-wrapper
  shortcode_wrapper_class: img-wrapper
  render_hook: false
  loading: lazy
  sizes: user #use only as override on inline/meta/page
  # placeholder: lqip/dominant/file_name 
  lqip_blur_amount: 5
  lqip_div_factor: 5
  gif_div_factor: 10
  # provider: netlify
  # suppress_width_warning: true
  type: page # or global
  min_width_difference: 40


# developer notes
