image:
  widths: [600, 900, 1300]
  # shortcodeWidths: [600, 900, 1300]
  # renderHookWidths: [600, 900, 1300]
  densities: [1, 2]
  formats: [original, webp]
  class: img-fluid
  figureClass: figure
  figcaptionClass: figure-caption
  figureImageClass: "figure-img img-fluid"
  figureTitleH: 4
  renderHookWrapperClass: img-wrapper
  shortcodeWrapperClass: img-wrapper
  renderHook: false
  loading: lazy
  sizes: user
  # placeholder: lqip/dominant/file_name 
  lqipBlurAmount: 5
  lqipDivFactor: 5
  gifDivFactor: 10
  # provider: netlify
  # suppressWidthWarning: true
  type: page # or global
  minWidthDifference: 40 # min px difference for image resize
